type User {
  username: String
  email: String @unique
  posts: [Post] @relation
}

type Post {
  user: User
  title: String
  date: String
  location: String
  description: String
  status: String
}

type AuthPayload {
  token: String!
  user: User!
}

type Query {
  users: [User]
  posts: [Post]
  userByEmail(email: String!): User
  postByTitle(title: String!): Post
}

type Mutation {
  loginUser(email: String!, password: String!): AuthPayload!
    @resolver(name: "loginUser")
  logoutUser: Boolean! @resolver(name: "logoutUser")
  createUser(email: String!, username: String!, password: String!): User!
    @resolver(name: "createUser")
}
